set-option -ga terminal-overrides ",xterm-256color:Tc"

# Options: start indexes from 1
set -g base-index 1
set -g pane-base-index 1

set -g renumber-windows on

# Change prefix
unbind C-b
set -g prefix `
bind ` send-prefix

# Status line
set -g status-style bg=#eeeeee,fg=black,bright
set -g status-left ""
set -g status-right "#[fg=black,bright]#S"

setw -g window-status-format " #I:#W "
setw -g window-status-current-format "#[bold,fg=black,bg=#c6f3c5] #I:#W #[default]"

# Popups
bind C-l display-popup \
  -d "#{pane_current_path}" \
  -w 80% \
  -h 80% \
  -E "lazygit"
bind C-n display-popup -E 'bash -i -c "read -p \"Session name: \" name; tmux new-session -d -s \$name && tmux switch-client -t \$name"'
bind C-j display-popup -E "tmux list-sessions | sed -E 's/:.*$//' | grep -v \"^$(tmux display-message -p '#S')\$\" | fzf --reverse | xargs tmux switch-client -t"
bind C-t display-popup \
  -d "#{pane_current_path}" \
  -w 75% \
  -h 75% \
  -E "zsh"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Initialize TPM
run-shell ~/.tmux/plugins/tpm/tpm

set-option -g @plugin 'b0o/tmux-autoreload'
