[tools]
neovim = "latest"
lazydocker = "latest"
node = "24"
python = "3.12"
just = "latest"
uv = "latest"

"npm:markdownlint-cli2" = "latest" # markdown lint + format
"npm:@fsouza/prettierd" = "latest" # yaml/html format
