after-startup-command = []

start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30

default-root-container-layout = 'tiles'

default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

automatically-unhide-macos-hidden-apps = false

[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 0
    inner.vertical =   0
    outer.left =       0
    outer.bottom =     0
    outer.top =        0
    outer.right =      0

[mode.main.binding]

    # Prevent Cmd+M from minimizing windows.
    cmd-m = 'exec-and-forget true'

    cmd-ctrl-alt-shift-slash = 'layout tiles horizontal vertical'
    cmd-ctrl-alt-shift-comma = 'layout accordion horizontal vertical'

    cmd-ctrl-alt-shift-h = 'focus left'
    cmd-ctrl-alt-shift-j = 'focus down'
    cmd-ctrl-alt-shift-k = 'focus up'
    cmd-ctrl-alt-shift-l = 'focus right'

    cmd-ctrl-alt-shift-minus = 'resize smart -50'
    cmd-ctrl-alt-shift-equal = 'resize smart +50'

    # Workspaces
    cmd-ctrl-alt-shift-1 = 'workspace 1'
    cmd-ctrl-alt-shift-2 = 'workspace 2'
    cmd-ctrl-alt-shift-3 = 'workspace 3'
    cmd-ctrl-alt-shift-4 = 'workspace 4'
    cmd-ctrl-alt-shift-5 = 'workspace 5'
    cmd-ctrl-alt-shift-6 = 'workspace 6'
    cmd-ctrl-alt-shift-7 = 'workspace 7'
    cmd-ctrl-alt-shift-8 = 'workspace 8'
    cmd-ctrl-alt-shift-9 = 'workspace 9'
    cmd-ctrl-alt-shift-a = 'workspace A'
    cmd-ctrl-alt-shift-b = 'workspace B'
    cmd-ctrl-alt-shift-c = 'workspace C'
    cmd-ctrl-alt-shift-d = 'workspace D'
    cmd-ctrl-alt-shift-e = 'workspace E'
    cmd-ctrl-alt-shift-f = 'workspace F'
    cmd-ctrl-alt-shift-g = 'workspace G'
    cmd-ctrl-alt-shift-i = 'workspace I'
    cmd-ctrl-alt-shift-m = 'workspace M'
    cmd-ctrl-alt-shift-n = 'workspace N'
    cmd-ctrl-alt-shift-o = 'workspace O'
    cmd-ctrl-alt-shift-p = 'workspace P'
    cmd-ctrl-alt-shift-q = 'workspace Q'
    cmd-ctrl-alt-shift-r = 'workspace R'
    cmd-ctrl-alt-shift-s = 'workspace S'
    cmd-ctrl-alt-shift-t = 'workspace T'
    cmd-ctrl-alt-shift-u = 'workspace U'
    cmd-ctrl-alt-shift-v = 'workspace V'
    cmd-ctrl-alt-shift-w = 'workspace W'
    cmd-ctrl-alt-shift-x = 'workspace X'
    cmd-ctrl-alt-shift-y = 'workspace Y'
    cmd-ctrl-alt-shift-z = 'workspace Z'

    cmd-ctrl-alt-shift-tab = 'workspace-back-and-forth'

    cmd-ctrl-alt-shift-space = 'mode move'

    cmd-ctrl-alt-shift-semicolon = 'mode service'

# Press Cmd+Ctrl+Alt+Shift+Space to enter move mode.
[mode.move.binding]
    esc = 'mode main'

    h = ['move left', 'mode main']
    j = ['move down', 'mode main']
    k = ['move up', 'mode main']
    l = ['move right', 'mode main']

    # Move the node to a workspace.
    1 = ['move-node-to-workspace 1', 'mode main']
    2 = ['move-node-to-workspace 2', 'mode main']
    3 = ['move-node-to-workspace 3', 'mode main']
    4 = ['move-node-to-workspace 4', 'mode main']
    5 = ['move-node-to-workspace 5', 'mode main']
    6 = ['move-node-to-workspace 6', 'mode main']
    7 = ['move-node-to-workspace 7', 'mode main']
    8 = ['move-node-to-workspace 8', 'mode main']
    9 = ['move-node-to-workspace 9', 'mode main']
    a = ['move-node-to-workspace A', 'mode main']
    b = ['move-node-to-workspace B', 'mode main']
    c = ['move-node-to-workspace C', 'mode main']
    d = ['move-node-to-workspace D', 'mode main']
    e = ['move-node-to-workspace E', 'mode main']
    f = ['move-node-to-workspace F', 'mode main']
    g = ['move-node-to-workspace G', 'mode main']
    i = ['move-node-to-workspace I', 'mode main']
    m = ['move-node-to-workspace M', 'mode main']
    n = ['move-node-to-workspace N', 'mode main']
    o = ['move-node-to-workspace O', 'mode main']
    p = ['move-node-to-workspace P', 'mode main']
    q = ['move-node-to-workspace Q', 'mode main']
    r = ['move-node-to-workspace R', 'mode main']
    s = ['move-node-to-workspace S', 'mode main']
    t = ['move-node-to-workspace T', 'mode main']
    u = ['move-node-to-workspace U', 'mode main']
    v = ['move-node-to-workspace V', 'mode main']
    w = ['move-node-to-workspace W', 'mode main']
    x = ['move-node-to-workspace X', 'mode main']
    y = ['move-node-to-workspace Y', 'mode main']
    z = ['move-node-to-workspace Z', 'mode main']

    tab = ['move-workspace-to-monitor --wrap-around next', 'mode main']

# Service mode
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
    esc = ['reload-config', 'mode main']
    r = ['flatten-workspace-tree', 'mode main'] # Reset the layout.
    f = ['layout floating tiling', 'mode main'] # Change between the floating and tiling layouts.
    backspace = ['close-all-windows-but-current', 'mode main']
    s = ['layout accordion horizontal vertical', 'mode main']
    t = ['layout tiles horizontal vertical', 'mode main']
    cmd-w = ['close --quit-if-last-window', 'mode main']

    alt-shift-h = ['join-with left', 'mode main']
    alt-shift-j = ['join-with down', 'mode main']
    alt-shift-k = ['join-with up', 'mode main']
    alt-shift-l = ['join-with right', 'mode main']

    down = 'volume down'
    up = 'volume up'
    shift-down = ['volume set 0', 'mode main']

[[on-window-detected]]
    if.app-id = 'com.github.wez.wezterm'
    run = 'move-node-to-workspace T' # T: Terminal

[[on-window-detected]]
    if.app-id = 'md.obsidian'
    run = 'move-node-to-workspace O' # O: Obsidian
