theme = "baked"

[editor]
line-number = "relative"
mouse = false
auto-format = true
popup-border = "all"
bufferline = "multiple"

[editor.statusline]
separator = "│"
mode.normal = "nor"
mode.insert = "ins"
mode.select = "sel"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal.space.t]
e = ":pipe-to reple eval"

[keys.select.space.t]
e = ":pipe-to reple eval"
