# --- language server definition ---
[language-server.clojure-lsp]
command = "clojure-lsp"

[language-server.svelte]
command = "svelteserver"
args = ["--stdio"]

# --- Language hookup ---
[[language]]
name = "clojure"
file-types = ["clj", "cljs", "cljc", "edn", "bb"]
roots = ["deps.edn", "project.clj", "bb.edn"]
language-servers = ["clojure-lsp"]
auto-format = true

[[language]]
name = "svelte"
file-types = ["svelte"]
language-servers = ["svelte"]

