[language-server.clojure-lsp]
command = "clojure-lsp"

[language-server.svelte]
command = "svelteserver"
args = ["--stdio"]

[language-server.tailwindcss]
command = "tailwindcss-language-server"
args = ["--stdio"]

[language-server.typescript-language-server]
command = "typescript-language-server"
args = ["--stdio"]

[[language]]
name = "clojure"
file-types = ["clj", "cljs", "cljc", "edn", "bb"]
roots = ["deps.edn", "project.clj", "bb.edn"]
language-servers = ["clojure-lsp"]
auto-format = true

[[language]]
name = "svelte"
file-types = ["svelte"]
language-servers = ["svelte"]

[[language]]
name = "typescript"
language-servers = ["typescript-language-server"]

[[language]]
name = "tsx"
language-servers = ["typescript-language-server", "tailwindcss"]

[[language]]
name = "javascript"
language-servers = ["typescript-language-server"]

[[language]]
name = "jsx"
language-servers = ["typescript-language-server", "tailwindcss"]

[[language]]
name = "html"
language-servers = ["tailwindcss"]

