(ns generators.common
  "Shared content for the per-tool generators.")

(def generated-banner
  "The theme generator created this file from the active theme/*.tokens.json. Do not edit this file manually.")
